Repository arnab2001/DSA, pull requests merged in 2021-10, with the labels that each got.

#10 add demo
  1500x500.jfif
  README.md
  images/logo-hacktoberfest-full.f42e3b1.svg
Labels: hacktoberfest-accepted

#16 Added Codes For Matrix and Doubly Linked List
  Linked List/doublylinkedlist.cpp
  Matrix/magic square
Labels: hacktoberfest-accepted

#17 Added Merge Sort
  array/Sorting and Searching/Merge_Sort_in_CPP.cpp
Labels: hacktoberfest-accepted

#15 Create 0-1knapsack.py
  Dynamic Programming/0-1knapsack.py
Labels: hacktoberfest-accepted

#14 Added Kotlin Binary Search
  Kotlin/BinarySearch
Labels: hacktoberfest-accepted

#13 added Queue Insertion
  queues/ENQueue.cpp
Labels: hacktoberfest-accepted

#11 added counting sort code
  Sorting/coutSort.cpp
Labels: hacktoberfest-accepted

#9 Radix sort in c with sample output
  Sorting/radixSort.c
Labels: hacktoberfest-accepted

#21 Added Euclidean GCD java code
  MathematicsDS/Euclidean GCD
Labels: hacktoberfest-accepted

#18 Added dequeue.cpp
  queues/Dequeue.cpp
Labels: hacktoberfest-accepted

#35 Jump Search added
  Searching/JumpSearch.java
Labels: hacktoberfest-accepted

#34 Added LCM of an array
  MathematicsDS/LCMofArray.java
Labels: hacktoberfest-accepted

#33 Super Ascii String Checker
  Largest Arithmetic Subarray
  String/Super ASCII string/superascii.c
Labels: hacktoberfest-accepted

#32 added matrix diagonalSum
  Matrix/diagonalSum.java
Labels: hacktoberfest-accepted

#31 Maximum Profit in Job Scheduling
  Dynamic Programming/Max_profit.cpp
Labels: hacktoberfest-accepted

#30 Added Bucket sort algorithm
  Sorting/bucketsort.py
Labels: hacktoberfest-accepted

#29 added trapping_Rain_water.java
  Linked List/trapping_Rain_water.java
  array/JAVA/rain_water_tapping
Labels: hacktoberfest-accepted

#28 Added Kadane's Algorithm
  array/Kadane's Algorithm.cpp
Labels: hacktoberfest-accepted

#27 Ashutosh added a cpp file for matrix multiplication.
  Matrix/Matrix_Multiplication.cpp
Labels: hacktoberfest-accepted

#26 LinearSearch_2DArray
  Linear Search in Matrix/LinearSearch_2DArray.java
Labels: hacktoberfest-accepted

#24 Added Longest Palindromic String
  String/Longest_Palindromic_String.cpp
Labels: hacktoberfest-accepted

#23 Largest Arithmetic Subarray
  array/Largest Arithmetic Subarray in C++.cpp
  array/Largest Arithmetic Subarray.md
Labels: hacktoberfest-accepted

#19 Create solution.c
  array/ArrayRotate/solution.c
Labels: hacktoberfest-accepted

#59 Create Modified Bubble sort.c
  Modified Bubble sort.c
Labels: hacktoberfest-accepted

#55 Added flip and invert a nxn matrix program
  array/JAVA/flipAndInvertImage.java
Labels: hacktoberfest-accepted

#54 JAVA ARRAYS
  array/Java Arrays/ArrayDeclationPractice.java
  array/Java Arrays/ArrayShortIncreasingOrder.java
  array/Java Arrays/Array_14_LeaderInArray.java
  array/Java Arrays/Array_Multipication.java
  array/Java Arrays/ArreyElements_AscendingOrder.java
  array/Java Arrays/AutomorphicNumber.java
  array/Java Arrays/CountDigit.java
  array/Java Arrays/LinearSearch.java
  array/Java Arrays/SumofLastAndFirstDigit.java
  array/Java Arrays/incert_delete.java
  array/Java Arrays/maximumDifferenceInArray.java
Labels: hacktoberfest-accepted

#53 added implementation and its various program code of binary search tree
  Binary search tree/deletion_in_bst.cpp
  Binary search tree/implement_part_2.cpp
  Binary search tree/implementation.cpp
Labels: hacktoberfest-accepted

#52 Added the code of Maximum sum Inc Subsequnce
  Dynamic Programming/Max_Sum_Inc_Subs.cpp
Labels: hacktoberfest-accepted

#49 Bellman Ford in C++
  graphs/bellmanFord.cpp
Labels: hacktoberfest-accepted

#48 Wave sort using C++
  Sorting/WaveSort.cpp
Labels: hacktoberfest-accepted

#45 Created Kruskals algorithm and max_heapsort.py
  Sorting/max_heapsort.py
  graphs/Kruskals_algorithm.py
Labels: hacktoberfest-accepted

#44 Created longest_palindromic_subsequence.cpp
  Dynamic Programming/longest_palindromic_subsequence.cpp
Labels: hacktoberfest-accepted

#43 Added few of my DSA codes in Java.
  Linked List/Java/LastToFront.java
  Linked List/Java/ReverseLinkedList.java
  String/Count.java
  String/Longest_subsequence.java
  array/JAVA/Move_neg_to_side.java
  array/JAVA/Sort_0_1_2.java
  graphs/Java/dijkstra.java
Labels: hacktoberfest-accepted

#42 Remove character from odd index
  String/string_remove_odd_position.c
Labels: hacktoberfest-accepted

#41 Create Binary Search.cpp
  array/Sorting and Searching/Binary Search.cpp
Labels: hacktoberfest-accepted

#39 add circular queue
  queues/circular queue.cpp
Labels: hacktoberfest-accepted

#83 complex_class
  class/complex_class.c++
Labels: hacktoberfest-accepted

#111 finding the combination sum
  Backtracking/backtracking.cpp
Labels: hacktoberfest-accepted

#114 Minimumdistance
  array/minimumdistance.c
Labels: hacktoberfest-accepted

#115 Implementation Of Stack
  Stack/implementationOfStack.cpp
Labels: hacktoberfest-accepted

#100 creating pull request
  Sorting/timsort.py
Labels: hacktoberfest-accepted

#62 adding multiple python sorting solutions
  Sorting/Python/bubbleSort.py
  Sorting/Python/insertionSort.py
  Sorting/Python/quickSort.py
  Sorting/Python/selectionSort.py
Labels: hacktoberfest-accepted

#66 added shellsort.c
  Sorting/shellsort.c
Labels: hacktoberfest-accepted

#68 Adding template codes
  Linked List/Circular linked list.cpp
  Matrix/sparse.cpp
  Matrix/tridiagonal matrix.cpp
Labels: hacktoberfest-accepted

#71 Create BinarySearch_SortedMatrix.Java
  Searching/BinarySearch_SortedMatrix.Java
Labels: hacktoberfest-accepted

#72 Create Tree_Sort.cpp
  array/Sorting and Searching/Tree_Sort.cpp
Labels: hacktoberfest-accepted

#80 longest common subsequence using c++
  Dynamic Programming/LongestCommonSubsequence.cpp
  Dynamic Programming/Unbounded_Knapsack.cpp
Labels: hacktoberfest-accepted

#84 added dutch national flag algorithm in cpp
  array/Dutch National Flag Algorithm/dutch-national-flag-algorithm.cpp
Labels: hacktoberfest-accepted

#85 Tower_of_hanoi
  recursion/tower_of_hanoi.c++
Labels: hacktoberfest-accepted

#86 Transpose of a Matrix
  Matrix/Transpose_Matrix.cpp
Labels: hacktoberfest-accepted

#87 coin change dp problem
  Dynamic Programming/coin_change.cpp
Labels: hacktoberfest-accepted

#88 added jumpsearch.py
  Searching/jumpsearch.py
Labels: hacktoberfest-accepted

#122 New code subset_sum_dp.cpp
  Dynamic Programming/code subset_sum_dp.cpp
Labels: hacktoberfest-accepted

#120 Added detect_loop_linked_list.cpp
  Linked List/detect_loop_linked_list.cpp
Labels: hacktoberfest-accepted

#119 added to DP
  Dynamic Programming/Kadane's Algorithm.cpp
Labels: hacktoberfest-accepted

#118 check a string having parenthsis are valid or not
  Stack/validparenthesis.cpp
Labels: hacktoberfest-accepted

#117 Create Sort the element in Stack using Recursion.cpp
  Stack/Sort the element in Stack using Recursion.cpp
Labels: hacktoberfest-accepted

#116 added stacks folder and wrote a program in it
  stacks/prog1_push_and_pop.c
Labels: hacktoberfest-accepted

#112 Insertion Sort added
  Sorting/insertionsort.py
Labels: hacktoberfest-accepted

#110 Added fil for Detect Loop in Linkedlist
  Linked List/Detect_Loop_in_Linkedlist.cpp
Labels: hacktoberfest-accepted

#107 Codes added related to 1D array
  Matrix/Searching in 2D Arraay.cpp
  array/Smallest_Missing_No.cpp
  array/Subarray_with_Sum_k.cpp
Labels: hacktoberfest-accepted

#106 Created longest_increasing_subsequence_dp.cpp
  Dynamic Programming/longest_increasing_subsequence_dp.cpp
Labels: hacktoberfest-accepted

#123 Added ternary search implementation
  Searching/ternary-search.cpp
Labels: hacktoberfest-accepted

#105 delete operation for two string leetcode problem
  Dynamic Programming/Delete_operation_for_two_strings.cpp
Labels: hacktoberfest-accepted

#104 Create Hackerrank-Arrays - Left Rotation.cpp
  array/Hackerrank-Arrays -  Left Rotation.cpp
Labels: hacktoberfest-accepted

#103 Created linearSearch.c & binarySearch.c
  Searching/binarySearch.c
  Searching/linearSearch.c
Labels: hacktoberfest-accepted

#102 kth largest element in array sol added
  .vscode/c_cpp_properties.json
  .vscode/settings.json
  array/kth Largest element/kth-largest-element-in-array.cpp
Labels: hacktoberfest-accepted

#101 Create del_in_linklist.cpp
  Linked List/del_in_linklist.cpp
Labels: hacktoberfest-accepted

#99 Added java code of GCD operations with matrix
  MathematicsDS/MatrixGCD.java
Labels: hacktoberfest-accepted

#98 Diagonal Matrix
  Matrix/DiagonalMatrix.cpp
Labels: hacktoberfest-accepted

#97 add bst searching
  Binary search tree/BST Seaching.cpp
Labels: hacktoberfest-accepted

#93 Create Insertionsort.cpp
  Sorting/Insertionsort.cpp
Labels: hacktoberfest-accepted

#94 I have added Questions based on Recursion solution using C and C++
  Recursion/C and C++/Indirect Recursion.c
  Recursion/C and C++/Nested Recursion
  Recursion/C and C++/Sum of N natural numbers.c
  Recursion/C and C++/Taylor Series horner rule and iterative methods
  Recursion/C and C++/Tree Recursion
  Recursion/C and C++/factorial of a number.c
  Recursion/C and C++/fibonacci.c
  Recursion/C and C++/global variable recursion.c
  Recursion/C and C++/head Recursion.cpp
  Recursion/C and C++/power using recursion.c
  Recursion/C and C++/static variables Recursion.cpp
  Recursion/C and C++/tail recursion.cpp
Labels: hacktoberfest-accepted

#95 Range Query with Segment Tree
  graphs/RangeQuerySegmentTree.cpp
Labels: hacktoberfest-accepted

#96 Added java version of QuickSort
  Sorting/QuickSort.java
Labels: hacktoberfest-accepted

#90 added minimum jumps to reach end in cpp
  array/Minimum number of Jumps To Reach End/minimum-number-of-jumps-to-reach-end.cpp
Labels: hacktoberfest-accepted

#92 Connected Components in a graph
  graphs/ConnectedComponents.cpp
Labels: hacktoberfest-accepted

#124 Create Sudoku_Backtracking.cpp
  Backtracking/Sudoku_Backtracking.cpp
Labels: hacktoberfest-accepted

#174 MergeKsortLinklist
  mergeKsortLinklist.cpp
Labels: hacktoberfest-accepted

#173 added subset generation backtracking algorithm C++
  Backtracking/generating_substes.cpp
Labels: hacktoberfest-accepted

#171 [Support] Added Segment Tree templates
  Segment Tree/RangeQuery-PointUpdate.cpp
  Segment Tree/RangeUpdate-PointQuery.cpp
Labels: hacktoberfest-accepted

#170 heapSort (CPP) array/sorting and searching
  array/Sorting and Searching/heapSort.cpp
Labels: hacktoberfest-accepted

#163 Created eratosthenes_sieve.cpp
  MathematicsDS/eratosthenes_sieve.cpp
Labels: hacktoberfest-accepted

#165 Added LinkedList in Javascript
  Linked List/Javascript/LinkedList.js
  Searching/Javascript/BinarySearch.js
Labels: hacktoberfest-accepted

#160 Add: BinarySearch in Javascript: #159
  Searching/Javascript/BinarySearch.js
Labels: hacktoberfest-accepted

#168 MinimumNumberOfDeletionsAndInsertions using c++
  Dynamic Programming/MinimumNumberOfDeletionsAndInsertions.cpp
Labels: hacktoberfest-accepted

#169 Solved bitmask on array of string
  Bitmasks/Pairs in array of string.cpp
Labels: hacktoberfest-accepted

#154 Create DP- Target Sum
  Dynamic Programming/DP- Target Sum
Labels: hacktoberfest-accepted

#155 Added BinaryExponentiation.java
  recursion/BinaryExponentiation.java
Labels: hacktoberfest-accepted

#157 Create Target sum subset solution.cpp
  Dynamic Programming/Target sum subset solution.cpp
Labels: hacktoberfest-accepted

#158 Create Remove Duplicate From Sorted List.cpp
  Linked List/Remove Duplicate From Sorted List.cpp
Labels: hacktoberfest-accepted

#162 added rotate matrix problem
  Matrix/Rotate matrix.cpp
Labels: hacktoberfest-accepted

#148 linearSearch.c and binarySearch.c added
  array/Sorting and Searching/binarySearch.c
  array/Sorting and Searching/linearSearch.c
Labels: hacktoberfest-accepted

#149 Create Binary_Search.cpp
  array/Sorting and Searching/Binary_Search.cpp
Labels: hacktoberfest-accepted

#151 Implemented Fraction class and its Basic methods using Java
  .classpath
  .gitignore
  .project
  class_JAVA/fraction/Fraction.java
  class_JAVA/fraction/FractionUse.java
Labels: hacktoberfest-accepted

#152 added sieve of Eratosthenes
  MathematicsDS/SieveOfErastosthenes.cpp
Labels: hacktoberfest-accepted

#153 Create seiveoferasthonis.cpp
  seiveoferasthonis.cpp
Labels: hacktoberfest-accepted

#142 Added codes for issues #77 and #79
  graphs/SingleCycleinGraph.cpp
  graphs/TraversingGridUsingdfs.cpp
Labels: hacktoberfest-accepted

#143 Implementatin of Tries added
  .vscode/settings.json
  Tries/Tries.cpp
Labels: hacktoberfest-accepted

#144 Add files via upload
  Dynamic Programming/Dynamic Programming/Abbrevation.py
  Dynamic Programming/Dynamic Programming/Abbreviation.java
  Dynamic Programming/Dynamic Programming/Candies.java
  Dynamic Programming/Dynamic Programming/Candies.py
  Dynamic Programming/Dynamic Programming/DecibinaryNumber.py
  Dynamic Programming/Dynamic Programming/DecibinaryNumbers.java
  Dynamic Programming/Dynamic Programming/MaxArraySum.py
  Dynamic Programming/Dynamic Programming/MaxSumArray.java
  Dynamic Programming/Dynamic Programming/abbreviation.cpp
  Dynamic Programming/Dynamic Programming/candies.cpp
  Dynamic Programming/Dynamic Programming/decibinary_numbers.cpp
  Dynamic Programming/Dynamic Programming/first.cpp
  Dynamic Programming/Dynamic Programming/max_array_sum.cpp
  Sorting/AnandSort.cpp
Labels: hacktoberfest-accepted

#145 Added Codes for #78 and #81
  MathematicsDS/Sieve of Eratothenes
  graphs/Check Whether Given Graph is Bipartite or Not
Labels: hacktoberfest-accepted

#146 to reverse linked list in cpp
  Linked List/to reverese a single linked list.cpp
Labels: hacktoberfest-accepted

#129 Retun Gift -1
  MathematicsDS/returngift.cpp
  MathematicsDS/separateno.cpp
Labels: hacktoberfest-accepted

#128 added naive pattern searching algorithm in c++
  String/naive_pattern_searching.cpp
Labels: hacktoberfest-accepted

#125 Added My Own BST Program without STL
  BST/bst.cpp
Labels: hacktoberfest-accepted

#175 added binary search in sorted matrix C++
  Matrix/binary search in a sorted matrix.cpp
Labels: hacktoberfest-accepted

#176 Longest repeating subsequence using c++
  Dynamic Programming/LongestRepeatingSubsequence.cpp
Labels: hacktoberfest-accepted

#178 Create LinkedListPalindrome.java
  LinkedListPalindrome.java
Labels: hacktoberfest-accepted

#177 Matrix addition in c++
  Matrix/matrix_addition
Labels: hacktoberfest-accepted

#275 Create Reverse Linked List.cpp
  Linked List/Reverse Linked List.cpp
Labels: Hacktoberfest

#274 Added Quick Sort and Ternary Search in Kotlin
  Kotlin/quicksort.kt
  Kotlin/ternary_search.kt
Labels: Hacktoberfest

#273 Added a cpp program to print top view of a binary tree
  Tree/Top_view_binary_tree.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#272 added reverse a string using stack
  Stack/Reverse a string using stack.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#271 Collections sort in java
  Sorting/JavaSort.java
Labels: Hacktoberfest, hacktoberfest-accepted

#270 Added Tower_of_Hanoi.cpp
  Tower_of_Hanoi.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#269 Time conversion code
  String/Time_conversion.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#268 NumberOfNodes: problem solution added
  Tree/NumberOfNodes.java
Labels: Hacktoberfest, hacktoberfest-accepted

#276 merge sort for linked list
  Linked List/Python/mergesort_for_linkedlist.py
Labels: hacktoberfest-accepted

#279 Huffmancoding
  huffmancoding.cpp
Labels: hacktoberfest-accepted

#278 RottingOranges:problem solution added
  graphs/Java/RottingOranges.java
Labels: hacktoberfest-accepted

#277 ThreeSumOfArray:problem solution added
  array/JAVA/ThreeSum.java
Labels: hacktoberfest-accepted

#281 Bubble Sort using Shell Script
  Sorting/bubblesort.sh
Labels: hacktoberfest-accepted

#283 Check Even And Odd using Bit Manipulation
  Bit manipulation/checkEvenOrOdd.cpp
  queues/QueueUsingStack.cpp
Labels: hacktoberfest-accepted
